# This workflow will build and release golang project

name: Binary release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # disable shallow clone - get all

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: stable
      id: go

    - name: Fetch build tag
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
      shell: /bin/bash -e {0}

    - name: Print build tag
      run: echo "Building release ${VERSION}"


    - name: Generate code
      run: make generate

    - name: Check for changes
      run: |
        git diff
        git diff-index --quiet HEAD

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
        workdir: .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
